"""Test fixtures as code — materialized into temp dirs at test time.

The agentize repo is a pure-Python CLI and ships zero non-Python files;
fixtures are generated on demand so the repository tree stays clean.
"""
import pathlib

FIXTURE_FILES: dict[str, str] = {
    "fixture_web/package.json": """\
{
  "name": "fixture-web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "test": "vitest run",
    "test:watch": "vitest",
    "lint": "eslint .",
    "typecheck": "tsc --noEmit",
    "format": "prettier --write ."
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0"
  },
  "devDependencies": {
    "typescript": "^5.5.0",
    "vitest": "^2.1.0",
    "eslint": "^9.0.0",
    "prettier": "^3.3.0"
  }
}
""",
    "fixture_web/tsconfig.json": """\
{
  "compilerOptions": {
    "strict": true,
    "target": "ES2022",
    "module": "ESNext",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
""",
    "fixture_web/README.md": """\
# Fixture Web App

A fake Next.js app used to test agentize. It renders a dashboard of widgets and exposes a small API.

## Development

Run `npm run dev` and open http://localhost:3000. The API lives in `src/api`.
""",
    "fixture_web/CONTRIBUTING.md": """\
# Contributing

Thanks for helping!

## Pull request process

- Always run `npm run lint` and `npm run typecheck` before pushing.
- Branch names: `fix/`, `feat/`, `chore/`.
- Never commit directly to `main`.

## Gotchas

- The dev server caches aggressively — if you see stale widgets, delete `.next` and restart.
- Do not edit `src/api/legacy.js`; it is generated by an upstream tool.
- Dates are UTC everywhere except the dashboard, which expects Asia/Karachi.
""",
    "fixture_web/.env.example": "\n".join([
        "DATABASE_URL=postgres://localhost:5432/fixture",
        "API_KEY=change-me",
        "NEXT_PUBLIC_SITE_URL=http://localhost:3000",
        "",
    ]),
    "fixture_web/.github/workflows/ci.yml": """\
name: CI
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
""",
    "fixture_ml/pyproject.toml": """\
[project]
name = "fixture-ml"
version = "0.1.0"
description = "A fake Python package for testing agentize."
requires-python = ">=3.10"
dependencies = ["pandas", "numpy"]

[project.scripts]
train = "fixture_ml.train:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 100

[tool.black]
line-length = 100
""",
    "fixture_ml/README.md": """\
# Fixture ML

A fake Python training package used to test agentize.

## Usage

Install with `uv sync`, then run `uv run train --config configs/base.yaml`.
""",
}


def materialize(name: str, base: pathlib.Path) -> pathlib.Path:
    """Write one fixture's files under `base` and return the fixture root."""
    root = base / name
    prefix = name + "/"
    for rel, content in FIXTURE_FILES.items():
        if not rel.startswith(prefix):
            continue
        p = root / rel[len(prefix):]
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
    return root
